```yaml
name: Metrics

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          user: paul-kimani
          template: classic
          base: header, activity, community, repositories, metadata

          config_timezone: Africa/Nairobi

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_details: percentage

          plugin_isocalendar: yes

          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_facts: yes

          plugin_lines: yes

          plugin_stars: yes

          plugin_followup: yes

          plugin_topics: yes
          plugin_topics_limit: 12

          plugin_notable: yes

          plugin_achievements: yes
          plugin_achievements_threshold: C

          plugin_activity: yes
          plugin_activity_limit: 5
```
